### ISSUE TITLE
Request: Some logging message when a server gets started

### ISSUE THREAD

**Issue by joamla96** [moritztng/hacker-league#10]
Some confirmation response from running the server confirming that it has started.
Would be nice if it would say something like:

server: Started at {ip} {port}

and some indicator if the public ip got submittet as well.

**Comment by moritztng** [comment]
Now it prints:
```bash
 $ ./server 5000
Server listening on address "0.0.0.0" (all interfaces) and port "5000"
```
And when you add public address and port:
```bash
$ ./server 5000 188.245.192.146 5000
Server listening on address "0.0.0.0" (all interfaces) and port "5000"
Publishing address "188.245.192.146" and port "5000" to public servers list
```
